spring:
  cloud:
    gateway:
      routes:
        - id: client-route
          uri: http://localhost:8080/
          predicates:
            - Path= /clients/**
        - id: account-route
          uri: http://localhost:8081/
          predicates:
            - Path= /accounts/**
        - id: operation-route
          uri: http://localhost:8082/
          predicates:
            - Path= /api/v1/operations/** , /operations/**
    discovery:
      enabled: true
  application:
    name: GATEWAY-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka
server:
  port: 8888
